### ISSUE TITLE
Failed to activate the lisp-paredit package

### ISSUE THREAD

**Issue by tvaquero** [jonspalding/lisp-paredit#1]
[Enter steps to reproduce below:]
1. After open Atom, the error below popped up.

**Atom Version**: 0.211.0
**System**: Ubuntu 14.04.2
**Thrown From**: [lisp-paredit](https://github.com/jonspalding/lisp-paredit) package, v0.3.0
### Stack Trace

Failed to activate the lisp-paredit package

```
At endless loop at {"idx":95876,"column":0,"row":1674}

Error: endless loop at {"idx":95876,"column":0,"row":1674}
    at readSeq ~/.atom/packages/lisp-paredit/node_modules/paredit.js/lib/reader.js:110:45)
    at readSexp (~/.atom/packages/lisp-paredit/node_modules/paredit.js/lib/reader.js:74:20)
    at readSeq (~/.atom/packages/lisp-paredit/node_modules/paredit.js/lib/reader.js:111:16)
    at readSexp (~/.atom/packages/lisp-paredit/node_modules/paredit.js/lib/reader.js:74:20)
    at readSeq (~/.atom/packages/lisp-paredit/node_modules/paredit.js/lib/reader.js:111:16)
    at Object.exports.reader.readSeq (~/.atom/packages/lisp-paredit/node_modules/paredit.js/lib/reader.js:12:14)
    at Object.exports.parse (~/.atom/packages/lisp-paredit/node_modules/paredit.js/index.js:20:32)
    at checkSyntax (~/.atom/packages/lisp-paredit/lib/main.coffee:119:19)
    at observeEditor (~/.atom/packages/lisp-paredit/lib/main.coffee:110:5)
    at ~/.atom/packages/lisp-paredit/lib/main.coffee:97:18
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
lisp-paredit, v0.3.0

# Dev
No dev packages
```

**Comment by sjlevine** [comment]
Hello,

@tvaquero and I actually work in the same lab, and have looked a little deeper into this. The error thrown in Atom is likely coming from `paredit.js` and could be related to parsing really big files. I've opened an issue for this here:
https://github.com/rksm/paredit.js/issues/4

Thanks again for your hard work!

Best,
Steve

**Comment by rksm** [comment]
Should be fixed now with paredit.js 0.2.10.

**Comment by britthard** [comment]
Still getting this error.  

OSX Yosemite: 10.10.02 
Atom: 1.0.7
lisp-paredit: 0.4.3

```
TypeError: Cannot read property 'dispose' of null
  at disableParedit (/Users/brittainchristopherhard/.atom/packages/lisp-paredit/lib/main.coffee:64:7)
  at /Users/brittainchristopherhard/.atom/packages/lisp-paredit/lib/main.coffee:41:9
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:555:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
  at Object.module.exports.LispParedit.activate (/Users/brittainchristopherhard/.atom/packages/lisp-paredit/lib/main.coffee:33:17)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:370:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)
```

Would love to use this package, any help is appreciated.

Edit: Maybe its worthy of another issue?

**Comment by jonspalding** [comment]
Looks like paredit.js 0.2.10 hasn't been pushed to NPM, I've opened an issue on that repo rksm/paredit.js#7.

**Comment by britthard** [comment]
thanks @jonspalding
